### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by hroncok** [encukou/jrti_game#1]
I've been playing for a while. Then I tried to grab something from a pile of bugs and move it left.

```console
$ jrti-game 
Traceback (most recent call last):
  File "/home/churchyard/tmp/__venv__/bin/jrti-game", line 11, in <module>
    sys.exit(main())
  File "/home/churchyard/tmp/__venv__/lib64/python3.6/site-packages/jrti_game/__init__.py", line 8, in main
    return main()
  File "/home/churchyard/tmp/__venv__/lib64/python3.6/site-packages/jrti_game/game.py", line 415, in main
    pyglet.app.run()
  File "/home/churchyard/tmp/__venv__/lib64/python3.6/site-packages/pyglet/app/__init__.py", line 143, in run
    event_loop.run()
  File "/home/churchyard/tmp/__venv__/lib64/python3.6/site-packages/pyglet/app/base.py", line 136, in run
    self._run_estimated()
  File "/home/churchyard/tmp/__venv__/lib64/python3.6/site-packages/pyglet/app/base.py", line 165, in _run_estimated
    timeout = self.idle()
  File "/home/churchyard/tmp/__venv__/lib64/python3.6/site-packages/pyglet/app/base.py", line 274, in idle
    redraw_all = self.clock.call_scheduled_functions(dt)
  File "/home/churchyard/tmp/__venv__/lib64/python3.6/site-packages/pyglet/clock.py", line 300, in call_scheduled_functions
    item.func(dt, *item.args, **item.kwargs)
  File "/home/churchyard/tmp/__venv__/lib64/python3.6/site-packages/jrti_game/game.py", line 399, in tick
    state.tool.move(dx, dy)
  File "/home/churchyard/tmp/__venv__/lib64/python3.6/site-packages/jrti_game/tool.py", line 156, in move
    g.parent.spawn_bug(g, s_to_homing=4)
AttributeError: 'NoneType' object has no attribute 'spawn_bug'
```

The GAME_DEBUG was not set and I'm afraid I cannot reproduce, because I was already playing for a while.

**Comment by encukou** [comment]
I don't know if I'll get around to fixing this in jrti: I set out to spend a week on it, not make a perfect game and maintain it forever.

Despite that, this report is quite helpful for my PyWeek goal: to learn more about how to make a game. I'll definitely keep issues with "disappearing parents" in mind for future games.
Thank you for taking the time to play and report the "buggy bugs" bug!
